---
name: Build and Package NPM Project as DMG

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-package:
    runs-on: macos-latest # macOS because we need MacOS to create DMG files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specify the Node version
  
      - name: Install the project
        run: npm install
  
      - name: Build the project
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload DMG to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/whatsapp_business-*.dmg
          compression-level: 0

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ github.run_number }}   # Или подставь свой tag/version
      #     name: Release v${{ github.run_number }}
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/whatsapp_business-*.dmg
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
